name: Pull Request

on:
  pull-request:
    branches:
      - master

jobs:
  xcodebuild:
    name: Blackboard Build
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode/Contents/Developer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod install --project-directory=Blackboard
    - name: Install enum
      run: pip install --upgrade pip enum34
    - name: xcodebuild
      run: xcodebuild -workspace Blackboard/Blackboard.xcworkspace -scheme Blackboard - configuration Debug -destination 'platform=iOS Simulator, name=iPhone 12, OS=14.3' test
